### PR TITLE
Fix missing 'id' field in FeliCa card reading on iOS

### PR DESCRIPTION
**Pull request by shiwano**
This will fix this issue https://github.com/nfcim/flutter_nfc_kit/issues/139

### CODE REVIEW

**Comment by Harry-Chen** [comment]
Thanks for your report and PR! I would like to confirm whether it is possible to read the id of iso18092 tags on iOS? @jiegec

**Comment by shiwano** [comment]
https://developer.apple.com/documentation/corenfc/nfcfelicatag
Based on my checks, it seems that it's not possible to retrieve something like a Tag ID (I'm not an expert on CoreNFC library, so there might be a possibility).

**Comment by jiegec** [comment]
I don't know FeliCa, but here is the relevant documentation: https://developer.apple.com/documentation/corenfc/nfcfelicatag

**Comment by Harry-Chen** [comment]
> I don't know FeliCa, but here is the relevant documentation: https://developer.apple.com/documentation/corenfc/nfcfelicatag

Yes I know that. I also notice that Felica tags have a UID. @dangfan Do you know how to read it?

**Comment by shiwano** [comment]
If there is a way to retrieve the Tag ID, please let me know. I can fix this PR and check that it works with my FeliCa card.

**Comment by Harry-Chen** [comment]
@shiwano Please refer to the following code:

https://github.com/RfidResearchGroup/proxmark3/blob/0eea4e31c4141a787e1f172e87cdea00b14237e8/client/src/cmdhffelica.c#L309-L346

This code sends `FELICA_CONNECT` command (0x01) to felica tag, and the data returned is in the format of `felica_select_t`:

https://github.com/RfidResearchGroup/proxmark3/blob/0eea4e31c4141a787e1f172e87cdea00b14237e8/include/iso18.h#L53-L61

Maybe you can try to read the `uid` (and even more data) using `sendFeliCaCommand`?

**Comment by shiwano** [comment]
Ok, I will try it 👍

**Comment by shiwano** [comment]
@Harry-Chen 

I've tried it and would like to share my findings.

Firstly, regarding the implementation in Proxmark3.

https://github.com/RfidResearchGroup/proxmark3/blob/0eea4e31c4141a787e1f172e87cdea00b14237e8/armsrc/felica.c#L276

The `uid` in `felica_card_select_t` appears to be the last 6 bytes of the IDm, so it's essentially the same as the IDm.
Since we can retrieve the IDm through `.currentIDm`, I think that part of the Proxmark3 implementation is not helpful for this PR.

---

Secondly, regarding the current implementation of ISO 18092 in flutter_nfc_kit for Android.
When I used an Android device to read a FeliCa card, I confirmed that the IDm was set to the tag's `id`,

https://github.com/nfcim/flutter_nfc_kit/blob/cc5c098700e618ba5629dbc33a00fce1cae12863/android/src/main/kotlin/im/nfc/flutter_nfc_kit/FlutterNfcKitPlugin.kt#L455

and the Manufacturer Parameter ([PMm](https://android.googlesource.com/platform/frameworks/base/+/d54f3f41c4b41955b7b4382a08b97a356b31fde4/core/java/android/nfc/tech/NfcF.java#71
)) was set to the `manufacturer`.

https://github.com/nfcim/flutter_nfc_kit/blob/cc5c098700e618ba5629dbc33a00fce1cae12863/android/src/main/kotlin/im/nfc/flutter_nfc_kit/FlutterNfcKitPlugin.kt#L537

On iOS, the `id` is unset, and the IDm is set to the `manufacturer`, which is different from the behavior on Android.

https://github.com/nfcim/flutter_nfc_kit/blob/cc5c098700e618ba5629dbc33a00fce1cae12863/ios/Classes/SwiftFlutterNfcKitPlugin.swift#L512

<details>
<summary>About IDm and PMm</summary>

https://www.sony.net/Products/felica/business/tech-support/data/M619_FeliCaTechnologyCodeDescriptions_1.6e.pdf

スクリーンショット 2023-12-23 0 58 20

スクリーンショット 2023-12-23 0 58 32

</details>

---

Based on this, I believe the correct approach for this PR is to set the IDm to the `id` and the PMm to the `manufacturer`. 
Does this make sense?

I've tried to implement that way.
When I tested it with my Felica card, as shown in the below images, I confirmed that both iOS and Android set the same values for `id` and `manufacturer`.

<details>
<summary>Android and iOS tested images</summary>

Screenshot_20231223-004800

IMG_1416

</details>

**Comment by Harry-Chen** [comment]
Thanks soooo much! And it would be great if you could further test other Felica related functionality in our library, since we do not have any tags available currently.

**Pull request merged**
