### PR TITLE
Android: fix freezes on transceive calls

### PR DESCRIPTION
**Pull request by cyberbobs**
As mentioned in [Android NFC documentation](https://developer.android.com/reference/android/nfc/tech/IsoDep#transceive(byte[])), transceive method is blocking and it causes UI freezes when called multiple times sequentially. This patch makes calls to transceive done in separate thread, while jumping to UI thread to return the result of the method call.

### CODE REVIEW

**Comment by Harry-Chen** [comment]
Thanks for pointing it out! Since we're using dart, will it work to simply wrap calls to `transceive` in [`compute`](https://api.flutter.dev/flutter/foundation/compute-constant.html)? This is platform-independent and could solve the same problem on iOS (if it exists).

**Comment by cyberbobs** [comment]
This probably wouldn't work. The call will still be triggered on Android UI thread (that processes the main event loop) and MethodResult should also be [called back on main thread](https://docs.flutter.dev/development/platform-integration/platform-channels#channels-and-platform-threading).

Didn't check the `trasceive` performance on iOS yet, but it will probably be less of an issue since any NFC communication on iOS shows bottom panel overlay and covers app window with tinted backdrop.

I'm not 100% sure about correctness of Kotlin threading code though (being neither Kotlin nor native Android developer), but it works, doesn't cause any additional troubles in our use cases and completely fixes the bad (like, really bad) stutter.

**Comment by Harry-Chen** [comment]
Ok, I understand now. The core problem is we shouldn't put the main thread on wait and return ASAP. 

Would you please use a class variable in `FlutterNfcKitPlugin` to store the handler (since it uses the main looper and will not change during the whole lifetime) and avoid creating it each time before posting a message back? The overhead is, I believe though, almost negligible, but it would be more elegant.

**Comment by Harry-Chen** [comment]
I actually noticed that in our code, we *are* using `MethodResultWrapper` to post the result back to main thread. So there is no need to create new `Handler` every time a method is invoked from Dart side.

https://github.com/nfcim/flutter_nfc_kit/blob/da9f28a6453aec115b10641179fc6305494cce4f/android/src/main/kotlin/im/nfc/flutter_nfc_kit/FlutterNfcKitPlugin.kt#L428-L450

I will add threading support on top of it.

**Pull request closed without merging**
